app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash

from app import db
from app.models import User


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and user.check_password(request.form['password']):
            session['username'] = user.username
            return redirect(url_for('home.homepage'))
        flash("Incorrect username or password", "danger")
    return render_template(
        template_name_or_list='login.html'
    )

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        if User.query.filter_by(username=username).first():
            flash("Username already taken.", "danger")
            return redirect(url_for('auth.register'))
        password = request.form['password']
        user = User(username=username, available_funds=10000)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        session['username'] = user.username
        return redirect(url_for('home.homepage'))
    return render_template(
        template_name_or_list='register.html'
    )

@auth.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('auth.login'))

app/routes/home.py
from bokeh.embed import components
from bokeh.plotting import figure
from bokeh.models import HoverTool, Legend
from bokeh.resources import CDN
from flask import Blueprint, redirect, render_template, session, url_for, request, jsonify

from app.utils.chess_api import get_elo_df, get_current_elo
from config import CHESS_MAPPING, LOIC_USERNAME


home = Blueprint('home', __name__)


@home.route('/')
def homepage():
    return redirect(url_for('home.elo_page'))


@home.route('/elo')
def elo_page():
    df = get_elo_df(session.get('selected_chess_com_tag', LOIC_USERNAME))

    # Création du plot Bokeh
    p = figure(
        x_axis_type='datetime',
        sizing_mode="stretch_width",
        height=400,
        tools="pan,wheel_zoom,box_zoom,reset,save"
    )

    line = p.line(df['Date'], df['ELO'], line_width=2)
    p.scatter(df['Date'], df['ELO'], size=4, marker="circle", fill_color="black")

    legend = Legend(items=[("Loïc Coin", [line])])
    legend.label_text_font_size = "13px"
    p.add_layout(legend, 'below')  # En dehors à droite

    p.xaxis.axis_label = 'Date'
    p.yaxis.axis_label = 'ELO'

    hover = HoverTool(
        tooltips=[("Date", "@x{%F %T}"), ("ELO", "@y")],
        formatters={'@x': 'datetime'},
        mode='vline'
    )
    p.add_tools(hover)

    script, div = components(p)
    cdn_js = CDN.js_files[0]
    cdn_css = CDN.css_files[0] if CDN.css_files else None

    return render_template(
        template_name_or_list='home.html',
        username=session.get('username'),
        elo_rapid=session.get(
            'selected_chess_com_tag_value',
            get_current_elo(
                session.get('selected_chess_com_tag', LOIC_USERNAME)
            )
        ),
        script=script,
        div=div,
        cdn_js=cdn_js,
        cdn_css=cdn_css,
        assets=list(CHESS_MAPPING.keys())
    )

@home.route('/update_selected_asset_for_home', methods=['POST'])
def update_selected_asset():
    data = request.get_json()
    selected_asset = data.get('asset')

    if not selected_asset:
        return jsonify({'status': 'error', 'message': 'No asset provided'}), 400

    session['selected_asset'] = selected_asset
    session['selected_chess_com_tag'] = CHESS_MAPPING[selected_asset]
    new_elo = get_current_elo(session.get('selected_chess_com_tag'))
    session['selected_chess_com_tag_value'] = new_elo

    df = get_elo_df(session.get('selected_chess_com_tag', LOIC_USERNAME))

    # Création du plot Bokeh
    p = figure(
        x_axis_type='datetime',
        sizing_mode="stretch_width",
        height=400,
        tools="pan,wheel_zoom,box_zoom,reset,save"
    )

    line = p.line(df['Date'], df['ELO'], line_width=2)
    p.scatter(df['Date'], df['ELO'], size=4, marker="circle", fill_color="black")

    legend = Legend(items=[("Loïc Coin", [line])])
    legend.label_text_font_size = "13px"
    p.add_layout(legend, 'below')  # En dehors à droite

    p.xaxis.axis_label = 'Date'
    p.yaxis.axis_label = 'ELO'

    hover = HoverTool(
        tooltips=[("Date", "@x{%F %T}"), ("ELO", "@y")],
        formatters={'@x': 'datetime'},
        mode='vline'
    )
    p.add_tools(hover)

    script, div = components(p)
    cdn_js = CDN.js_files[0]
    cdn_css = CDN.css_files[0] if CDN.css_files else None

    return jsonify(
        {
            'status': 'ok', 'selected': selected_asset, 'elo_rapid': new_elo,
            'script': script, 'div': div
        }
    )

app/routes/leaderboard.py
from flask import Blueprint, render_template, session

from app.models import User
from app.utils.chess_api import get_current_elo
from config import CHESS_MAPPING, LOIC_USERNAME


leaderboard = Blueprint('leaderboard', __name__)


@leaderboard.route('/leaderboard')
def leaderboard_page():
    users = User.query.all()

    leaderboard_data = []
    for user in users:
        equity = user.get_equity()
        loic_coin_qty = sum(pos.quantity for pos in user.open_positions if pos.asset == 'Loïc_Coin')

        leaderboard_data.append({
            'username': user.username,
            'equity': equity,
            'loic_coin_qty': loic_coin_qty
        })

    # Tri + classement
    leaderboard_data.sort(key=lambda x: x['equity'], reverse=True)
    current_rank = 1
    ranked = []
    for i, player in enumerate(leaderboard_data):
        player['rank'] = ranked[-1]['rank'] if i > 0 and player['equity'] == ranked[-1]['equity'] else current_rank
        ranked.append(player)
        current_rank += 1

    return render_template(
        template_name_or_list='leaderboard.html',
        username=session.get('username'),
        elo_rapid=session.get(
            'selected_chess_com_tag_value',
            get_current_elo(
                session.get('selected_chess_com_tag', LOIC_USERNAME)
            )
        ),
        leaderboard=ranked,
        assets=list(CHESS_MAPPING.keys())
    )

app/routes/trade.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, jsonify

from app import db
from app.models import User, EloHistory
from app.utils.chess_api import get_current_elo
from config import CHESS_MAPPING, LOIC_USERNAME

trade = Blueprint('trade', __name__)


@trade.route('/trade', methods=['GET', 'POST'])
def trading_page():
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    user = User.query.filter_by(username=session['username']).first() # SaNsE
    EloHistory.update_assets()

    # assets = EloHistory.get_all_assets_name()
    assets = list(CHESS_MAPPING.keys())
    selected_asset = session.get('selected_asset', 'Loïc_Coin')

    # We want to put selected_asset in first position
    if selected_asset in assets:
        assets.remove(selected_asset)
    assets.insert(0, selected_asset)

    if request.method == 'POST':
        if request.form.get('open_position') == '1':
            try:
                quantity = float(request.form.get('quantity'))
                if quantity == 0:
                    flash("Quantity cannot be zero.", "danger")
                    return redirect(url_for('trade.trading_page'))
            except ValueError:
                flash("Invalid quantity format.", "danger")
                return redirect(url_for('trade.trading_page'))

            error = user.open_position()
            flash("Position opened!" if not error else error, "success" if not error else "danger")
            return redirect(url_for('trade.trading_page'))

        if request.form.get('close_position') == '1':
            user.close_position(request.form.get('position_id'))
            return redirect(url_for('trade.trading_page'))

    positions = [
        {
        'id': pos.id,
        'asset': pos.asset,
        'quantity': pos.quantity,
        'entry_price': pos.entry_price,
        'position_value': pos.get_position_value()
        }
        for pos in user.open_positions
    ]

    return render_template(
        template_name_or_list='trade.html',
        username=user.username,
        elo_rapid=session.get(
            'selected_chess_com_tag_value',
            get_current_elo(
                session.get('selected_chess_com_tag', LOIC_USERNAME)
            )
        ),
        assets=assets,
        positions=positions,
        available_funds=user.available_funds
    )


@trade.route('/force/<int:value>')
def force_value(value):
    """Force un nouvel ELO pour un asset donné"""
    new_entry = EloHistory(asset="Loïc_Coin", elo=value)
    db.session.add(new_entry)
    db.session.commit()
    return redirect(url_for('trade.trading_page'))


# @trade.route('/give', methods=['GET', 'POST'])
# def give():
#     user = User.query.filter_by(username=session['username']).first()
#     user.available_funds += 500
#     db.session.commit()
#     return render_template('OK - 500 coins added')

@trade.route('/update_selected_asset', methods=['POST'])
def update_selected_asset():
    data = request.get_json()
    selected_asset = data.get('asset')

    if not selected_asset:
        return jsonify({'status': 'error', 'message': 'No asset provided'}), 400

    session['selected_asset'] = selected_asset
    session['selected_chess_com_tag'] = CHESS_MAPPING[selected_asset]
    new_elo = get_current_elo(session.get('selected_chess_com_tag'))
    session['selected_chess_com_tag_value'] = new_elo
    return jsonify({'status': 'ok', 'selected': selected_asset, 'elo_rapid': new_elo})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {% block title %} Loïc Coin {% endblock %} </title>

    <!-- Custom fonts for this template-->
    <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('home.homepage') }}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3"> Loïc Coin </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <div class="sidebar-heading">
                OVERVIEW
            </div>

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home.homepage') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('leaderboard.leaderboard_page') }}">
                    <i class="fa fa-gamepad"></i>
                    <span>Leaderboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            {% if username %}
                <div class="sidebar-heading">
                    MARKET
                </div>

                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('trade.trading_page') }}">
                        <i class="fa fa-university"></i>
                        <span>Trade</span></a>
                </li>
            {% endif %}

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% block topbar %}
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if username %}
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 large"> {{ username }} </span>
                                {%  endif %}
                                <i class="fa fa-user-secret fa-lg fa-fw mr-2 icon-blue"></i>
                            </a>
                           <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">

                                {% if username %}
                                    <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Logout
                                    </a>
                                {% else %}
                                    <a class="dropdown-item" href="{{ url_for('auth.login') }}">
                                        <i class="fas fa-sign-in-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Login
                                    </a>
                                {% endif %}

                            </div>
                        </li>
                    </ul>
                </nav>
                {% endblock %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {% block content %}
                    <div> Example </div>
                    {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span> Loïc Coin &copy; Updated in July 2025</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Bootstrap core JavaScript-->
    <script src="../static/vendor/jquery/jquery.min.js"></script>
    <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../static/js/sb-admin-2.min.js"></script>

</body>

</html>

app/templates/base_with_elo.html
{% extends "base.html" %}

{% block topbar %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <div class="ml-2 my-auto">
        <form method="post" id="topbarAssetForm" class="mb-0">
            <div class="d-flex align-items-center border-left-primary rounded shadow-sm px-2"
                 style="height: 48px; background-color: #f8f9fc; min-width: 100px; max-width: 180px;">

                <select class="form-control form-control-sm border-0 bg-transparent text-dark font-weight-bold p-0"
                        id="topbarAssetSelect"
                        style="font-size: 0.85rem;">
                    {% for asset in assets %}
                        <option value="{{ asset }}" {% if asset == session['selected_asset'] %}selected{% endif %}>
                            {{ asset }}
                        </option>
                    {% endfor %}
                </select>

            </div>
        </form>
    </div>

    <div class="elo-block ml-2 mr-3 my-auto">
        <div class="card border-left-primary shadow" style="height: 48px; min-width: 200px;">
            <div class="card-body py-1 px-3 d-flex align-items-center h-100">
                <div class="row no-gutters align-items-center w-100">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1" style="line-height: 1;">
                            ELO Rapid
                        </div>
                        <div class="h6 mb-0 font-weight-bold text-gray-800" id="eloRapid">
                            {{ elo_rapid }}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-flag fa-lg text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if username %}
                    <span class="mr-2 d-none d-lg-inline text-gray-600 large"> {{ username }} </span>
                {%  endif %}
                <i class="fa fa-user-secret fa-lg fa-fw mr-2 icon-blue"></i>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">

                {% if username %}
                    <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                {% else %}
                    <a class="dropdown-item" href="{{ url_for('auth.login') }}">
                        <i class="fas fa-sign-in-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Login
                    </a>
                {% endif %}

            </div>
        </li>
    </ul>
</nav>

{%  endblock %}

app/templates/close_position.html
<!-- <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Close Positions</title>
</head>
<body>
    <h1>Liste des positions ouvertes</h1>

    {% if positions %}
        <table border="1">
            <thead>
                <tr>
                    <th>Position number</th>
                    <th>Asset</th>
                    <th>Quantity</th>
                    <th>Entry Price</th>
                    <th>Close</th>
                </tr>
            </thead>
            <tbody>
                {% for position in positions %}
                    <tr>
                        <td>{{ position.id }}</td>
                        <td>{{ position.asset }}</td>
                        <td>{{ position.quantity }}</td>
                        <td>{{ position.entry_price }}</td>
                        <td>
                            <form method="POST" action="/close_pos">
                                <input type="hidden" name="position_id" value="{{ position.id }}">
                                <button type="submit">Close</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucune position ouverte.</p>
    {% endif %}
    <br>
    <a href="/">Retour à l'accueil</a>
</body>
</html> -->

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <title>Positions ouvertes</title>
    <style>
        table, th, td {
            border: 1px solid black; 
            border-collapse: collapse;
            padding: 8px;
        }
        th {
            background-color: #f0f0f0;
        }
        .funds {
            margin-top: 15px;
            font-weight: bold;
            font-size: 1.1em;
        }
    </style>
</head>
<body>
    <h2>Positions ouvertes</h2>
    {% if positions %}
    <table>
        <thead>
            <tr>
                <th>Position number</th>
                <th>Asset</th>
                <th>Quantity</th>
                <th>Entry price</th>
                <th>Position value</th>
                <th>Close</th>
            </tr>
        </thead>
        <tbody>
            {% for pos in positions %}
            <tr>
                <td>{{ pos.id }}</td>
                <td>{{ pos.asset }}</td>
                <td>{{ pos.quantity }}</td>
                <td>{{ pos.entry_price }}</td>
                <td>{{ "%.2f"|format(pos.position_value) }}</td>
                <td>
                    <form method="POST" action="{{ url_for('close_position', position_id=pos.id) }}">
                        <button type="submit">Close</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="funds">
        Available funds: {{ available_funds }}
    </div>

    {% else %}
    <p>Aucune position ouverte.</p>
    <div class="funds">
        Available funds: {{ available_funds }}
    </div>
    {% endif %}
</body>
</html>

app/templates/leaderboard.html
{% extends "base_with_elo.html" %}

{% block title %} Loïc Coin - Leaderboard {%  endblock %}

{% block content %}
<!-- Leaderboard Card -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary text-white">
        <h6 class="m-0 font-weight-bold">🏆 Leaderboard</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead class="table-light">
                    <tr>
                        <th style="width: 50px;">#</th>
                        <th>Player</th>
                        <th>Equity</th>
                        <th><i class="fas fa-coins text-warning"></i> Coins</th>
                    </tr>
                </thead>
                <tbody>
                    {% for player in leaderboard %}
                        <tr style="{% if player.rank == 1 %}
                              background-color: rgba(255, 215, 0, 0.15);
                               {% elif player.rank == 2 %}
                                  background-color: rgba(192, 192, 192, 0.15);
                               {% elif player.rank == 3 %}
                                  background-color: rgba(205, 127, 50, 0.15);
                               {% endif %}">
                            <td class="text-center align-middle">
                                {% if player.rank == 1 %}
                                    <i class="fa fa-crown" style="color: #FFD43B;"></i>
                                {% elif player.rank == 2 %}
                                    <i class="fa fa-crown" style="color: #C0C0C0;"></i>
                                {% elif player.rank == 3 %}
                                    <i class="fa fa-crown" style="color: #CD7F32;"></i>
                                {% else %}
                                    <span class="badge rounded-pill bg-light text-dark border border-1 border-secondary">
                                        #{{ player.rank }}
                                    </span>
                                {% endif %}
                            </td>
                            <td style="max-width:50px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;" title="{{ player.username }}">
                                <div class="d-flex align-items-center">
{#                                    <div class="rounded-circle bg-primary text-white d-flex justify-content-center align-items-center me-2" style="width: 36px; height: 36px; font-size: 14px;">#}
{#                                        {{ player.username[0]|upper }}#}
{#                                    </div>#}
                                    {{ player.username }}
                                </div>
                            </td>
                            <td>
                                <span class="text-success fw-bold">{{ "%0.f"|format(player.equity) }}</span>
                            </td>
                            <td>
                                <i class="fas fa-coins text-warning"></i>
                                {{ "%.1f"|format(player.loic_coin_qty) }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const topbarSelect = document.getElementById("topbarAssetSelect");

        // Synchronise le topbar vers le formulaire
        if (topbarSelect) {
            topbarSelect.addEventListener("change", function () {
                const selected = this.value;

                // Optionnel : mise à jour serveur si nécessaire
                fetch('/update_selected_asset', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ asset: selected })
                })
                .then(res => res.json())
                .then(data => {
                    if (data.elo_rapid) {
                        document.getElementById("eloRapid").textContent = data.elo_rapid;
                    }
                });

                // Facultatif : soumettre le formulaire topbar si nécessaire
                // document.getElementById("topbarAssetForm").submit();
            });
        }
    });
</script>

{% endblock %}

{##}
{#<!DOCTYPE html>#}
{#<html lang="fr">#}
{#<head>#}
{#    <meta charset="UTF-8" />#}
{#    <title>Leaderboard</title>#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet" />#}
{#</head>#}
{#<body class="p-4">#}
{##}
{#    <h2 class="mb-4">Top 10 sorted by Equity</h2>#}
{##}
{#    <table class="table table-striped table-bordered">#}
{#        <thead class="thead-dark">#}
{#            <tr>#}
{#                <th>Nom du user</th>#}
{#                <th>Equity</th>#}
{#                <th>Quantity Loïc_Coin</th>#}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#            {% for player in leaderboard %}#}
{#            <tr>#}
{#                <td>{{ player.username }}</td>#}
{#                <td>{{ "%.2f"|format(player.equity) }}</td>#}
{#                <td>{{ "%.2f"|format(player.loic_coin_qty) }}</td>#}
{#            </tr>#}
{#            {% endfor %}#}
{#        </tbody>#}
{#    </table>#}
{##}
{#    <a href="{{ url_for('home') }}">Back to home</a>#}
{##}
{#</body>#}
{#</html>#}

app/templates/trade_and_positions.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <title>Trade & Positions</title>
    <style>
        table, th, td {
            border: 1px solid black; 
            border-collapse: collapse;
            padding: 8px;
        }
        th {
            background-color: #f0f0f0;
        }
        .funds {
            margin-top: 15px;
            font-weight: bold;
            font-size: 1.1em;
        }
        form {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <h2>Current Assets Values</h2>

    <table border="1" cellpadding="5" cellspacing="0" style="max-width: 600px;">
        <thead>
            <tr>
                <th>Asset</th>
                <th>Current Value</th>
            </tr>
        </thead>
        <tbody>
            {% for item in assets_values %}
            <tr>
                <td>{{ item.asset }}</td>
                <td>{{ "%.2f"|format(item.value) }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="{{ url_for('trade') }}" method="get" style="margin-top: 10px; text-align: left;">
        <input type="hidden" name="update" value="1" />
        <button type="submit">Update</button>
    </form>

    <hr>

    <h2>Open a Position</h2>
    <form method="post">
        <input type="hidden" name="open_position" value="1" />
        <label for="asset">Choose an asset:</label><br>
        <select name="asset" required>
            {% for asset in assets %}
                <option value="{{ asset }}">{{ asset }}</option>
            {% endfor %}
        </select><br><br>
        <input type="number" step="any" name="quantity" placeholder="Quantity (e.g. 1.5)" required><br><br>
        <input type="submit" value="Open Position">
    </form>

    <h2>Open Positions</h2>

    {% if positions %}
    <table>
        <thead>
            <tr>
                <th>Position number</th>
                <th>Asset</th>
                <th>Quantity</th>
                <th>Entry price</th>
                <th>Position value</th>
                <th>Close</th>
            </tr>
        </thead>
        <tbody>
            {% for pos in positions %}
            <tr>
                <td>{{ pos.id }}</td>
                <td>{{ pos.asset }}</td>
                <td>{{ pos.quantity }}</td>
                <td>{{ pos.entry_price }}</td>
                <td>{{ "%.2f"|format(pos.position_value) }}</td>
                <td>
                    <form method="post" style="margin:0;">
                        <input type="hidden" name="close_position" value="1" />
                        <input type="hidden" name="position_id" value="{{ pos.id }}" />
                        <button type="submit">Close</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No open position.</p>
    {% endif %}

    <div class="funds">
        Available funds: {{ available_funds }}
    </div>
</body>
</html>